### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by mhrabiee** [snappmarket/frontend-toolbox#243]
Demo returns not found, please update it.

**Comment by rezaerami** [comment]
hello dear @mhrabiee .
unfortunately, the netlify service restricted our project so we are unable to have a demo, but you can clone the project and using `yarn && yarn docz:dev` run the demo on your local.
the default port is set to 9002 so after running you can see it on `localhost:9002`

**Comment by mhrabiee** [comment]
Oh i guess so. Thanks
